layout_spectrum: 0.02985075
color:
  saturation: 0.07086998
  lightness: 0.4773306
  brandStrength: 0.6602196
  rhythmicContrast: 0.05305736
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
typography_spectrum: 0.2361887
name: Robert_Mañé
