collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
typography_spectrum: 0.1921642
color:
  saturation: 0.1091418
  brandStrength: 0.6602196
  lightness: 0.03684701
  brandColors:
    - '#EAE3DD'
    - '#E79202'
    - '#445B03'
    - '#DC591F'
    - '#2A1B25'
  rhythmicContrast: 0.1669776
layout_spectrum: 0.02985075
name: Robert_Mañé
